### ISSUE TITLE
Help finding 'key'

### ISSUE THREAD

**Issue by shiffman** [IonicaBizau/learning-jwt#1]
Hello there!  This repo is incredibly helpful.  I'm following the instructions and have completed these steps:

* "Create Client ID" from google console.
* Convert the downloaded key to PEM
* Replace the `keyFile.pem` file with the generated file.

But I'm stuck on "Set your data in authData.json."

In the google console I see:

* Client ID: `864689................11n99t3tlnku1.apps.googleusercontent.com`
* Email address: `86468.................9t3tlnku1@developer.gserviceaccount.com`
* Certificate fingerprints: `91b982b....................3b7d52cece5` – Delete

It looks like I have the e-mail for [authData.json](https://github.com/IonicaBizau/learning-jwt/blob/master/authData.json), but I'm not sure where I find the `key`?

**Comment by shiffman** [comment]
Ok, apologies I think I see now that the key is in the JSON file which I need to download along with the pem file.  I'm getting an error, but I think that's just because I haven't authorized the directory_v1 API.  (I'm working on getting the youtube uploader to work here: https://github.com/IonicaBizau/youtube-api/issues/20).

**Comment by IonicaBizau** [comment]
@shiffman Glad you found the solution! :smile: Yes, the JSON file contains this info. Maybe, I should clarify that in docs.

**Comment by IonicaBizau** [comment]
Just clarifying: you can use the `pem` file **xor** the `private_key` from the json file. In this example, I use the `pem` file, showing how to generate it. In #2 I made the steps clearer. :four_leaf_clover:
